spring:
  mvc:    pathmatch:      matching-strategy:  ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: "default"
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
topic:
  schema_topic: t.transaction.schema
  transaction_topic: t.transaction
  account_topic: t.transaction.account
  transaction_account_topic: t.transaction.account_response